language: bash

before_script:
  - pip install --user awscli

script:
  - export TS=`date +"%s"`
  - travis/packer build -var "ts=${TS}" packer.json
  - mkdir -p ecs-ci-ami/default
  - for region in `cat aws_regions.txt`; do echo `aws ec2 --region=$region describe-images --filter "Name=tag:coldbrew_cli_created,Values=${TS}" | jq -r ".Images[0].ImageId"` > ecs-ci-ami/default/$region; done
  - ls -la ecs-ci-ami/default/

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: files.coldbrewcloud.com
  region: us-west-2
  acl: public_read
  skip_cleanup: true
  local_dir: ecs-ci-ami
  upload-dir: coldbrew-cli/ecs-ci-ami
  detect_encoding: true
