language: bash

before_script:
  - pip install --user awscli
  - export TS=`date +"%s"`
  - mkdir -p ecs-ci-ami/default
  - export IMAGE_VERSION=`cat VERSION`

script:
  - travis_wait 30 travis/packer build -var "ts=${TS}" -var "image_version=${IMAGE_VERSION}" -var "aws_region=${AWS_DEFAULT_REGION}" -var "source_ami=${SOURCE_AMI}" packer.json
