language: bash

before_script:
  - pip install --user awscli
  - export TS=`date +"%s"`
  - mkdir -p ecs-ci-ami/default

script:
  - travis/packer build -var "ts=${TS}" -var "aws_region=${AWS_DEFAULT_REGION}" -var "source_ami=${SOURCE_AMI}" packer.json
  - IMAGE_ID=`aws ec2 describe-images --filter "Name=tag:coldbrew_cli_created,Values=${TS}" | jq -r ".Images[0].ImageId"`
  - AMI_NAME=`aws ec2 describe-images --filter "Name=tag:coldbrew_cli_created,Values=${TS}" | jq -r ".Images[0].Name"`
  - SOURCE_REGION=${DEFAULT_AWS_REGION} SOURCE_IMAGE_NAME=${AMI_NAME} SOURCE_IMAGE_ID=${IMAGE_ID} ./deploy.sh
  - ls -la ecs-ci-ami/default/

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: files.coldbrewcloud.com
  region: us-west-2
  acl: public_read
  skip_cleanup: true
  local_dir: ecs-ci-ami
  upload-dir: coldbrew-cli/ecs-ci-ami
  detect_encoding: true
